spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/good?serverTimezone=Asia/Seoul
    username: good
    password: "!123456"

  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp